### ISSUE TITLE
Do not recommend this mod? 

### ISSUE THREAD

**Issue by iVirtualPlays** [Zekfoo/tactileAGB#1]
I attempted to install this mod but could not get it to fit, almost damaged my GBA. It’s too thick and puts lot of pressure and flex on the motherboard pcb, also the button will not click right at times. It has to almost be perfectly lined up to get the right click. I recommend getting an SP if you want clicky buttons. Overall membranes are better for long term reliability, no soldering necessary to get them working compared to tactile.

**Comment by Zekfoo** [comment]
Thickness shouldn't be an issue if you've ordered the boards as flex PCBs as stated in the description.
As with all hardware mods, you run the risk of damage to your devices if not handled properly.
